'use strict';

const fs = require('fs');
const path = require('path');

const EXTENSION_MAP = {
  '.py': 'Python',
  '.pyw': 'Python',
  '.js': 'JavaScript',
  '.mjs': 'JavaScript',
  '.cjs': 'JavaScript',
  '.jsx': 'JavaScript',
  '.ts': 'TypeScript',
  '.tsx': 'TypeScript',
  '.c': 'C',
  '.h': 'C',
  '.cpp': 'C++',
  '.cc': 'C++',
  '.cxx': 'C++',
  '.hpp': 'C++',
  '.hh': 'C++',
  '.hxx': 'C++',
  '.rs': 'Rust',
  '.go': 'Go',
  '.java': 'Java',
  '.kt': 'Kotlin',
  '.scala': 'Scala',
  '.cs': 'C#',
  '.fs': 'F#',
  '.vb': 'VB.NET',
  '.swift': 'Swift',
  '.m': 'Objective-C',
  '.mm': 'Objective-C++',
  '.rb': 'Ruby',
  '.php': 'PHP',
  '.lua': 'Lua',
  '.r': 'R',
  '.jl': 'Julia',
  '.pl': 'Perl',
  '.pm': 'Perl',
  '.sh': 'Shell',
  '.bash': 'Shell',
  '.zsh': 'Shell',
  '.ps1': 'PowerShell',
  '.sql': 'SQL',
  '.dart': 'Dart',
  '.ex': 'Elixir',
  '.exs': 'Elixir',
  '.erl': 'Erlang',
  '.hrl': 'Erlang',
  '.hs': 'Haskell',
  '.clj': 'Clojure',
  '.cljs': 'Clojure',
  '.ml': 'OCaml',
  '.mli': 'OCaml',
  '.zig': 'Zig',
  '.html': 'HTML',
  '.htm': 'HTML',
  '.css': 'CSS',
  '.scss': 'SCSS',
  '.sass': 'SCSS',
  '.less': 'Less',
  '.vue': 'Vue',
  '.svelte': 'Svelte',
  '.astro': 'Astro',
  '.json': 'JSON',
  '.jsonc': 'JSON',
  '.yaml': 'YAML',
  '.yml': 'YAML',
  '.toml': 'TOML',
  '.xml': 'XML',
  '.md': 'Markdown',
  '.markdown': 'Markdown',
  '.txt': 'Text',
};

const CONFIG_FILES = [
  { name: 'package.json', lang: 'JSON' },
  { name: 'pyproject.toml', lang: 'TOML' },
  { name: 'requirements.txt', lang: 'Python' },
  { name: 'Cargo.toml', lang: 'TOML' },
  { name: 'CMakeLists.txt', lang: 'CMake' },
  { name: 'Makefile', lang: 'Makefile' },
  { name: 'pom.xml', lang: 'XML' },
  { name: 'build.gradle', lang: 'Gradle' },
  { name: 'build.gradle.kts', lang: 'Gradle' },
  { name: 'go.mod', lang: 'Go' },
  { name: 'Package.swift', lang: 'Swift' },
  { name: 'pubspec.yaml', lang: 'YAML' },
  { name: 'Dockerfile', lang: 'Dockerfile' },
  { name: 'compose.yml', lang: 'YAML' },
  { name: 'docker-compose.yml', lang: 'YAML' },
  { name: 'package-lock.json', lang: 'JSON' },
  { name: 'yarn.lock', lang: 'Text' },
  { name: 'pnpm-lock.yaml', lang: 'YAML' },
  { name: '.gitignore', lang: 'Text' },
  { name: '.prettierrc', lang: 'JSON' },
  { name: '.eslintrc', lang: 'JSON' },
  { name: '.eslintrc.json', lang: 'JSON' },
  { name: 'tsconfig.json', lang: 'JSON' },
  { name: 'vite.config.ts', lang: 'TypeScript' },
  { name: 'webpack.config.js', lang: 'JavaScript' },
];

function languageForFile(name, relPath) {
  const lower = name.toLowerCase();
  const config = CONFIG_FILES.find((c) => c.name.toLowerCase() === lower);
  if (config) return config.lang;
  const ext = path.extname(name).toLowerCase();
  return EXTENSION_MAP[ext] || 'Text';
}

const LANGUAGE_ICONS = {
  Python: 'Py',
  JavaScript: 'JS',
  TypeScript: 'TS',
  C: 'C',
  'C++': 'C++',
  Rust: 'Rs',
  Go: 'Go',
  Java: 'Jv',
  Kotlin: 'Kt',
  'C#': 'C#',
  Swift: 'Sw',
  Ruby: 'Rb',
  PHP: 'Ph',
  JSON: '{}',
  YAML: 'Ya',
  TOML: 'To',
  HTML: '<>',
  CSS: '##',
  SCSS: '##',
  Vue: 'Vue',
  Svelte: 'Sv',
  Dart: 'Dart',
  Shell: '>_',
  SQL: 'SQL',
  Markdown: 'MD',
  Text: 'TXT',
};

module.exports = { languageForFile, EXTENSION_MAP, CONFIG_FILES, LANGUAGE_ICONS };
